var projects = [
	[
		{url: "wang_residence/wang_residence_01.jpg", 
			text1: "The Wang Residence", 
			text2: "Location: 41st Deer Creek Lane, Danville, CA", 
			text3: ""},
		{url: "wang_residence/wang_residence_02.jpg", 
			text1: "The Wang Residence", 
			text2: "Front and Back View", 
			text3: ""},
		{url: "wang_residence/wang_residence_03.jpg", 
			text1: "The Wang Residence", 
			text2: "Side View", 
			text3: ""},
		{url: "wang_residence/wang_residence_living.jpg", 
			text1: "The Wang Residence", 
			text2: "Living Room", 
			text3: ""},
		{url: "wang_residence/wang_residence_stairway.jpg", 
			text1: "The Wang Residence", 
			text2: "Stairway", 
			text3: ""},
		{url: "wang_residence/wang_residence_bathroom.jpg", 
			text1: "The Wang Residence", 
			text2: "Bathroom", 
			text3: ""}
	], [
		{url: "saratoga_home/front.jpg", 
			text1: "Saratoga Home", 
			text2: "Front View", 
			text3: ""},
		{url: "saratoga_home/floor_plan.png", 
			text1: "Saratoga Home", 
			text2: "Floor Plan", 
			text3: ""},
		{url: "saratoga_home/construction_1.jpg", 
			text1: "Saratoga Home", 
			text2: "Front Entrance", 
			text3: ""},
		{url: "saratoga_home/construction_2.jpg", 
			text1: "Saratoga Home", 
			text2: "Garage", 
			text3: ""},
		{url: "saratoga_home/construction_3.jpg", 
			text1: "Saratoga Home", 
			text2: "Backyard", 
			text3: ""},
		{url: "saratoga_home/construction_4.jpg", 
			text1: "Saratoga Home", 
			text2: "Front View", 
			text3: ""}
	], [
		{url: "saratoga_home_2/saratoga_home_2-front1.jpg", 
			text1: "Saratoga Home 2", 
			text2: "Front View",
			text3: ""},
		{url: "saratoga_home_2/saratoga_home_2-front2.jpg", 
			text1: "Saratoga Home 2", 
			text2: "Front View",
			text3: ""},
		{url: "saratoga_home_2/saratoga_home_2-front3.jpg", 
			text1: "Saratoga Home 2", 
			text2: "Front View",
			text3: ""},
		{url: "saratoga_home_2/saratoga_home_2-interior1.jpg", 
			text1: "Saratoga Home 2", 
			text2: "Interior View",
			text3: ""},
		{url: "saratoga_home_2/saratoga_home_2-interior2.jpg", 
			text1: "Saratoga Home 2", 
			text2: "Interior View",
			text3: ""},
		{url: "saratoga_home_2/saratoga_home_2-interior3.jpg", 
			text1: "Saratoga Home 2", 
			text2: "Interior View",
			text3: ""},
		{url: "saratoga_home_2/saratoga_home_2-interior4.jpg", 
			text1: "Saratoga Home 2", 
			text2: "Interior View",
			text3: ""},
		{url: "saratoga_home_2/KIRAN_PLAN_ELEV.png", 
			text1: "Saratoga Home 2", 
			text2: "Site Plan",
			text3: ""}
	], [
		{url: "berkeley_home/THE BERKELEY PROJECT 2020.jpg", 
			text1: "Berkeley Home", 
			text2: "", 
			text3: ""},
		{url: "berkeley_home/berkeley_home_side.jpg", 
			text1: "Berkeley Home", 
			text2: "Ground View",
			text3: ""},
		{url: "berkeley_home/berkeley_home_top.jpg", 
			text1: "Berkeley Home", 
			text2: "Top View", 
			text3: ""},
		{url: "berkeley_home/berkeley_home_multi.jpg", 
			text1: "Berkeley Home", 
			text2: "Multiple Units", 
			text3: ""}
	], [
		{url: "emeryville/EXTERIOR_AFTER_FULL.jpg", 
			text1: "Emeryville Home Remodel", 
			text2: "After Remodel", 
			text3: ""},
		{url: "emeryville/EXTERIOR_BEFORE.jpg", 
			text1: "Emeryville Home Remodel", 
			text2: "Before Remodel", 
			text3: "Location: Emeryville, CA"},
		{url: "emeryville/1ST_FLOOR_AFTER.jpg", 
			text1: "Emeryville Home Remodel", 
			text2: "1st Floor After Remodel", 
			text3: ""},
		{url: "emeryville/1ST_FLOOR_BEFORE.jpg", 
			text1: "Emeryville Home Remodel", 
			text2: "1st Floor Before Remodel", 
			text3: ""},
		{url: "emeryville/2ND_FLOOR_AFTER.jpg", 
			text1: "Emeryville Home Remodel", 
			text2: "2nd Floor After Remodel", 
			text3: ""},
		{url: "emeryville/2ND_FLOOR_BEFORE.jpg", 
			text1: "Emeryville Home Remodel", 
			text2: "2nd Floor Before Remodel", 
			text3: ""}
	], [
		{url: "santaclara_home_1/3493 exterior1.jpg", 
			text1: "The Guballa Residence", 
			text2: "Site Area: 6060 Square Feet, Building Area: 3200 Square Feet", 
			text3: "Location: San Francisco Bay Area, CA"},
		{url: "santaclara_home_1/3493 exterior2new.jpg", 
			text1: "The Guballa Residence", 
			text2: "Exterior", 
			text3: ""},
		{url: "santaclara_home_1/3493 exterior3.jpg", 
			text1: "The Guballa Residence", 
			text2: "Exterior", 
			text3: ""},
		{url: "santaclara_home_1/3493 exterior4.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior1.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior2.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior3.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior4.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior5.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior6.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior7.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior8.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/3493 interior9.jpg", 
			text1: "The Guballa Residence", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_1/construction_1.jpg", 
			text1: "The Guballa Residence", 
			text2: "Construction", 
			text3: ""},
		{url: "santaclara_home_1/GUBALLA_RESIDENCE_PLANS.jpg", 
			text1: "The Guballa Residence", 
			text2: "Plans", 
			text3: ""}
	], [
		{url: "santaclara_home_2/exterior1SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "Location: Santa Clara, CA", 
			text3: ""},
		{url: "santaclara_home_2/exterior2SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/exterior4SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/exterior6SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/exterior7SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/exterior66.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/interior 1.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/interior 4SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/interior 5SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/interior 6SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/interior8SM.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/SANTA_CLARA_HOME_2_ANGLE.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/santa_clara_home_1.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: ""},
		{url: "santaclara_home_2/santa_clara_home_ interior.jpg", 
			text1: "Santa Clara Home", 
			text2: "", 
			text3: "Interior View"},
		{url: "santaclara_home_2/SANTA_CLARA_HOME_2_FRONT_ELEV-1.png", 
			text1: "Santa Clara Home", 
			text2: "Front Elevation", 
			text3: ""},
		{url: "santaclara_home_2/SANTA_CLARA_HOME_2_SIDE_ELEV-1.png", 
			text1: "Santa Clara Home", 
			text2: "Side Elevation", 
			text3: ""},
		{url: "santaclara_home_2/SANTA_CLARA_HOME_2_PLANS-1.png", 
			text1: "Santa Clara Home", 
			text2: "Floor Plans", 
			text3: ""},
		{url: "santaclara_home_2/SANTA_CLARA_HOME_2_SITE_PLAN-1.png", 
			text1: "Santa Clara Home", 
			text2: "Site Plans", 
			text3: ""},
	], [	
		{url: "santaclara_home_3/front1.jpg", 
			text1: "Santa Clara Home", 
			text2: "Location: Santa Clara, CA", 
			text3: ""},
		{url: "santaclara_home_3/front2.jpg", 
			text1: "Santa Clara Home", 
			text2: "Location: Santa Clara, CA", 
			text3: "Front View"},
		{url: "santaclara_home_3/front3.jpg", 
			text1: "Santa Clara Home", 
			text2: "Location: Santa Clara, CA", 
			text3: "Front View"},
		{url: "santaclara_home_3/back1.jpg", 
			text1: "Santa Clara Home", 
			text2: "Back View", 
			text3: ""},
		{url: "santaclara_home_3/top1.jpg", 
			text1: "Santa Clara Home", 
			text2: "Side Elevation", 
			text3: "Top View"},
		{url: "santaclara_home_3/top2.jpg", 
			text1: "Santa Clara Home", 
			text2: "Floor Plans", 
			text3: "Top View"}
	], [	
		{url: "santaclara_home_4/front1.jpg", 
			text1: "Santa Clara Home", 
			text2: "Location: Santa Clara, CA", 
			text3: "Front View"},
		{url: "santaclara_home_4/front2.jpg", 
			text1: "Santa Clara Home", 
			text2: "Location: Santa Clara, CA", 
			text3: "Front View"},
		{url: "santaclara_home_4/ext1.jpg", 
			text1: "Santa Clara Home", 
			text2: "Location: Santa Clara, CA", 
			text3: "Front View"},
		{url: "santaclara_home_4/ext5.jpg", 
			text1: "Santa Clara Home", 
			text2: "Back View", 
			text3: ""},
		{url: "santaclara_home_4/ext7.jpg", 
			text1: "Santa Clara Home", 
			text2: "Main Entrance", 
			text3: ""},
		{url: "santaclara_home_4/ext8.jpg", 
			text1: "Santa Clara Home", 
			text2: "Main Entrance", 
			text3: ""},
		{url: "santaclara_home_4/int1.jpg", 
			text1: "Santa Clara Home", 
			text2: "Interior 1", 
			text3: ""},
		{url: "santaclara_home_4/int4.jpg", 
			text1: "Santa Clara Home", 
			text2: "Interior 2", 
			text3: ""},
		{url: "santaclara_home_4/int5.jpg", 
			text1: "Santa Clara Home", 
			text2: "Interior 3", 
			text3: ""},
		{url: "santaclara_home_4/int11.jpg", 
			text1: "Santa Clara Home", 
			text2: "Interior 4", 
			text3: ""},
		{url: "santaclara_home_4/int12.jpg", 
			text1: "Santa Clara Home", 
			text2: "Interior 5", 
			text3: ""},
	],
	[
		{url: "fremont_home_1/1designrendering.jpg", 
			text1: "Fremont Home", 
			text2: "Rendered Concept", 
			text3: ""},
		{url: "fremont_home_1/0before.jpg", 
			text1: "Fremont Home", 
			text2: "Before Construction", 
			text3: ""},
		{url: "fremont_home_1/construction0.webp", 
			text1: "Fremont Home", 
			text2: "During Construction", 
			text3: ""},
		{url: "fremont_home_1/construction1.webp", 
			text1: "Fremont Home", 
			text2: "During Construction 2", 
			text3: ""},
		{url: "fremont_home_1/construction2.webp", 
			text1: "Fremont Home", 
			text2: "During Construction 3", 
			text3: ""},
		{url: "fremont_home_1/ext1.webp", 
			text1: "Fremont Home", 
			text2: "Construction Finished", 
			text3: ""},
		{url: "fremont_home_1/ext3.webp", 
			text1: "Fremont Home", 
			text2: "Construction Finished - Front View", 
			text3: ""},
		{url: "fremont_home_1/ext2.webp", 
			text1: "Fremont Home", 
			text2: "Construction Finished - Back View", 
			text3: ""},
		{url: "fremont_home_1/int1.webp", 
			text1: "Fremont Home", 
			text2: "Interior - Main Hall", 
			text3: ""},
		{url: "fremont_home_1/int2.webp", 
			text1: "Fremont Home", 
			text2: "Interior - Stairway", 
			text3: ""},
		{url: "fremont_home_1/int3.webp", 
			text1: "Fremont Home", 
			text2: "Interior - Stairway 2", 
			text3: ""},
		{url: "fremont_home_1/int4.webp", 
			text1: "Fremont Home", 
			text2: "Interior - Kitchen", 
			text3: ""},
		{url: "fremont_home_1/int5.webp", 
			text1: "Fremont Home", 
			text2: "Interior", 
			text3: ""},
		{url: "fremont_home_1/int6.webp", 
			text1: "Fremont Home", 
			text2: "Interior - Bathroom", 
			text3: ""},

	],
	[
		{url: "walnut_creek/AFTER1.jpg", 
			text1: "Walnut Creek House", 
			text2: "Addition Rendered Concept", 
			text3: ""},
		{url: "walnut_creek/AFTER2.jpg", 
			text1: "Walnut Creek House", 
			text2: "Addition Rendered Concept", 
			text3: ""},
		{url: "walnut_creek/BEFORE1.jpg", 
			text1: "Walnut Creek House", 
			text2: "Before Addition", 
			text3: "Location: Contra Costa County, CA"},
		{url: "walnut_creek/WALNUT_CREEK_HOME_PLANS_new.png", 
			text1: "Walnut Creek House", 
			text2: "Floor Plan", 
			text3: "Location: Contra Costa County, CA"}
	], [
		{url: "belmont_home_2/SCENE_6_LOT.jpg", 
			text1: "Belmont Home", 
			text2: "Lot View", 
			text3: "Location: Belmont, CA"},
		{url: "belmont_home_2/helen_house.jpg", 
			text1: "Belmont Home",
			text2: "Side View",
			text3: ""},
		{url: "belmont_home_2/Belmont_elevation_front_2.png", 
			text1: "Belmont Home", 
			text2: "Front Elevation", 
			text3: ""},
		{url: "belmont_home_2/Belmont_elevation_side_2.png", 
			text1: "Belmont Home", 
			text2: "Side Elevation", 
			text3: ""},
		{url: "belmont_home_2/Belmont_site_plan.jpg", 
			text1: "Belmont Home", 
			text2: "Site Plan", 
			text3: ""}
	], [
		{url: "cupertino_home/AFTER_02.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Angled Front View", 
			text3: ""},
		{url: "cupertino_home/AFTER_01.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Front View", 
			text3: ""},
 		{url: "cupertino_home/BEFORE_01.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Front View", 
			text3: ""},
		{url: "cupertino_home/AFTER_04b.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Kitchen", 
			text3: ""},
		{url: "cupertino_home/BEFORE_3.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Kitchen", 
			text3: ""},
		{url: "cupertino_home/AFTER_05.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Stairway", 
			text3: ""},
		{url: "cupertino_home/BEFORE_05.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Stairway", 
			text3: ""},
		{url: "cupertino_home/peng_plan.jpg", 
			text1: "Cupertino Home Expansion", 
			text2: "Floor Plan", 
			text3: ""}
	], [
		{url: "cupertino_home_2/front1.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Front View", 
			text3: ""},
		{url: "cupertino_home_2/front2.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Front View", 
			text3: ""},
		{url: "cupertino_home_2/front3.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Front View", 
			text3: ""},
		{url: "cupertino_home_2/front4.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Front View", 
			text3: ""},
		{url: "cupertino_home_2/front5.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Front View", 
			text3: ""},
		{url: "cupertino_home_2/hall1.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Hallway", 
			text3: ""},
		{url: "cupertino_home_2/interior1.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Interior", 
			text3: ""},
		{url: "cupertino_home_2/interior2.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Kitchen", 
			text3: ""},
		{url: "cupertino_home_2/interior3.jpg", 
			text1: "Cupertino Home 2", 
			text2: "View to Backyard",
			text3: ""},
		{url: "cupertino_home_2/interior4.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Interior", 
			text3: ""},
		{url: "cupertino_home_2/bathroom1.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Bathroom", 
			text3: ""},
		{url: "cupertino_home_2/bathroom2.jpg", 
			text1: "Cupertino Home 2", 
			text2: "Bathroom", 
			text3: ""}
	], [
		{url: "sanjose_home/front1.jpg", 
			text1: "San Jose Home", 
			text2: "Front", 
			text3: ""},
		{url: "sanjose_home/front3.jpg", 
			text1: "San Jose Home", 
			text2: "Front", 
			text3: ""},
		{url: "sanjose_home/front2.jpg", 
			text1: "San Jose Home", 
			text2: "Front", 
			text3: ""},
		{url: "sanjose_home/sj1-2.jpg", 
			text1: "San Jose Home", 
			text2: "Side", 
			text3: ""},
		{url: "sanjose_home/sj1-3.jpg", 
			text1: "San Jose Home", 
			text2: "Living Room", 
			text3: ""},
		{url: "sanjose_home/sj1-4.jpg", 
			text1: "San Jose Home", 
			text2: "Stairs",
			text3: ""},
		{url: "sanjose_home/sj1-5.jpg", 
			text1: "San Jose Home",
			text2: "Kitchen",
			text3: ""},
		{url: "sanjose_home/sj1-6.jpg",
			text1: "San Jose Home",
			text2: "Stairs",
			text3: ""},
		{url: "sanjose_home/sj1-7.jpg",
			text1: "San Jose Home",
			text2: "Second Floor",
			text3: ""},
		{url: "sanjose_home/sj1-8.jpg", 
			text1: "San Jose Home", 
			text2: "Bathroom", 
			text3: ""}
	], [
		{url: "san_ramon_home_exp/BEFORE.jpg", 
			text1: "San Ramon Home", 
			text2: "Front - Before", 
			text3: ""},
		{url: "san_ramon_home_exp/AFTER-1.jpg", 
			text1: "San Ramon Home", 
			text2: "Front - After", 
			text3: ""},
		{url: "san_ramon_home_exp/AFTER-2.jpg", 
			text1: "San Ramon Home", 
			text2: "Front/Side", 
			text3: ""},
		{url: "san_ramon_home_exp/AFTER-3.jpg", 
			text1: "San Ramon Home", 
			text2: "Interior", 
			text3: ""},
		{url: "san_ramon_home_exp/AFTER-4.jpg", 
			text1: "San Ramon Home", 
			text2: "Interior", 
			text3: ""},
		{url: "san_ramon_home_exp/AFTER-5.jpg", 
			text1: "San Ramon Home", 
			text2: "Interior", 
			text3: ""},
		{url: "san_ramon_home_exp/AFTER-6.jpg", 
			text1: "San Ramon Home", 
			text2: "Interior", 
			text3: ""},
		{url: "san_ramon_home_exp/AFTER-7.jpg", 
			text1: "San Ramon Home", 
			text2: "Interior", 
			text3: ""},
	], [
		{url: "sc county home exp 1/s.c.county 1-1.jpg", 
			text1: "Santa Clara County", 
			text2: "", 
			text3: ""},
		{url: "sc county home exp 1/s.c.county 1-2.jpg", 
			text1: "Santa Clara County", 
			text2: "", 
			text3: ""},
		{url: "sc county home exp 1/s.c.county 1-3.jpg", 
			text1: "Santa Clara County", 
			text2: "", 
			text3: ""},
		{url: "sc county home exp 1/s.c.county 1-4.jpg", 
			text1: "Santa Clara County", 
			text2: "", 
			text3: ""}
	], [
		{url: "adu_el_cerrito/before_after.jpg", 	
			text1: "El Cerrito Garage", 	
			text2: "Before and After", 	
			text3: ""},
		{url: "adu_el_cerrito/interior_construction_1.jpg", 	
			text1: "El Cerrito Garage", 	
			text2: "Construction", 	
			text3: ""},
		{url: "adu_el_cerrito/interior_1.jpg", 	
			text1: "El Cerrito Garage", 	
			text2: "Interior", 	
			text3: ""},
		{url: "adu_el_cerrito/interior_2.jpg", 	
			text1: "El Cerrito Garage", 	
			text2: "Interior", 	
			text3: ""},
		{url: "adu_el_cerrito/interior_3.jpg", 	
			text1: "El Cerrito Garage", 	
			text2: "Interior", 	
			text3: ""}	
	], [
		{url: "pleasanton_home_1/EXT-1.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Front View Extension Completed", 	
			text3: ""},
		{url: "pleasanton_home_1/BEFORE.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Before Extension", 	
			text3: ""},
		{url: "pleasanton_home_1/EXT-2.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Front View", 	
			text3: ""},
		{url: "pleasanton_home_1/EXT-3.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Angle View", 	
			text3: ""},
		{url: "pleasanton_home_1/INT-0.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Kitchen", 	
			text3: ""},
		{url: "pleasanton_home_1/INT-2.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Stairs and Second Floor", 	
			text3: ""},
		{url: "pleasanton_home_1/INT-3.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Games Room", 	
			text3: ""},
		{url: "pleasanton_home_1/INT-4.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Living Room", 	
			text3: ""},
		{url: "pleasanton_home_1/INT-5.jpg", 	
			text1: "Pleasanton Home Extension", 	
			text2: "Bathroom", 	
			text3: ""}
	], [
		{url: "menlo_park_poolside_adu/EXT-1.jpg", 	
			text1: "Menlo Park - Poolside ADU", 	
			text2: "Backyard ADU Pool View", 	
			text3: ""},
		{url: "menlo_park_poolside_adu/EXT-2.webp", 	
			text1: "Menlo Park - Poolside ADU", 	
			text2: "ADU Side View", 	
			text3: ""},
		{url: "menlo_park_poolside_adu/INT-1.webp", 	
			text1: "Menlo Park - Poolside ADU", 	
			text2: "Interior View", 	
			text3: ""},
		{url: "menlo_park_poolside_adu/INT-2.webp", 	
			text1: "Menlo Park - Poolside ADU", 	
			text2: "Bathroom View", 	
			text3: ""},
		{url: "menlo_park_poolside_adu/INT-3.webp", 	
			text1: "Menlo Park - Poolside ADU", 	
			text2: "Folding Door View", 	
			text3: ""},
		{url: "menlo_park_poolside_adu/INT-4.webp", 	
			text1: "Menlo Park - Poolside ADU", 	
			text2: "Door Open", 	
			text3: ""},
	]
]

let titleArray = [
	"The Wang Residence",
	"Saratoga Home",
	"Saratoga Home 2",
	"Berkeley Home Project",
	"Emeryville Home Remodel",
	"Santa Clara Home 1-The Guballa Residence",
	"Santa Clara Home 2",
	"Santa Clara Home 3",
	"Santa Clara Home 4",
	"Fremont Home",

	"Walnut Creek House Addition",
	"Belmont Homes, California",
	"Cupertino Home Expansion",
	"Cupertino Home 2",
	"San Jose Home",
	"San Ramon Home",
	"Santa Clara County Home 1 Project",
	"El Cerrito Garage Project",
	"Pleasanton Home",
	"Menlo Park Poolside ADU",
]

for (let i = 0; i < titleArray.length; i++) {
	projects[i].title = titleArray[i];
}

projects[15].shownImage=1;



