var projects = [
	[
		{url: "inner_mongolia/01.jpg", 
			text1: "Inner-Mongolia Tourist's Building-Hotel/Shopping/Museum/Office Complex", 
			text2: "Site Area: 15,521 SM Building Area: 31,000 SM", 
			text3: "Positioning Company: Beijing Qing Gu Yin Xiang Environmental Planning and Design"},
		{url: "inner_mongolia/02.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
		{url: "inner_mongolia/03.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
		{url: "inner_mongolia/04.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
		{url: "inner_mongolia/05.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
		{url: "inner_mongolia/06.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
		{url: "inner_mongolia/07.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
		{url: "inner_mongolia/08.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
		{url: "inner_mongolia/09.jpg", 
			text1: "Inner-Mongolia Tourist's Building", 
			text2: "", 
			text3: ""},
	],
]

projects[0].title="Inner-Mongolia Tourist's Building";
