var projects = [
	[
		{url: "tri_valley_chinese/DESIGN_RENDERING_sanctuary_2.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "Remodel Project", 
			text3: "Sanctuary Concept Image"},
		{url: "tri_valley_chinese/DESIGN_RENDERING_sanctuary_1.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "Remodel Project", 
			text3: "Sanctuary Concept Image"},
		{url: "tri_valley_chinese/church_sanctuary.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "Church Sanctuary", 
			text3: ""}, 
		{url: "tri_valley_chinese/BEFORE1.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "Before Remodel", 
			text3: ""},
		{url: "tri_valley_chinese/BEFORE2.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "Before Remodel", 
			text3: ""},
		{url: "tri_valley_chinese/AFTER1.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "After Remodel", 
			text3: ""},
		{url: "tri_valley_chinese/AFTER2.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "After Remodel", 
			text3: ""},
		{url: "tri_valley_chinese/AFTER3.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "After Remodel", 
			text3: ""},
		{url: "tri_valley_chinese/EXISTING_FLOOR_PLAN.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "Remodel Project", 
			text3: "Existing Floor Plan"},
		{url: "tri_valley_chinese/NEW_FLOOR_PLAN.jpg",
			text1: "Tri Valley Chinese Bible Church", 
			text2: "Remodel Project", 
			text3: "New Floor Plan"} 
	],
	[
		{url: "mushan_hou/mushan_hou_1.jpg", 
			text1: "Mushan Hou Church", 
			text2: "Wenzhou, China", 
			text3: ""},
		{url: "mushan_hou/mushan_hou_2.jpg",
			text1: "Mushan Hou Church", 
			text2: "Wenzhou, China", 
			text3: ""},
		{url: "mushan_hou/03.jpg",
			text1: "Mushan Hou Church", 
			text2: "Wenzhou, China", 
			text3: ""},
		{url: "mushan_hou/04.jpg",
			text1: "Mushan Hou Church", 
			text2: "Wenzhou, China", 
			text3: ""}
	]
]

projects[0].title="Tri Valley Chinese Bible Church";
projects[1].title="Mushan Hou";